services:
  backend-json:
    build:
      context: backend-json
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  gradio-service:
    build:
      context: gradio-json
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    depends_on:
      - backend-json
